version: "3.2"

services:

  mongo:
    image: mongo
    restart: always
    volumes:
      - type: volume
        source: mongodb_data_volume
        target: /data/db
    ports:
      - 27017:27017


  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example


volumes:
  mongodb_data_volume: